---
- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - apt-utils
      - curl
      - gnupg
      - htop
      - unzip
      - xz-utils
    state: present
    update_cache: true

- name: Download e install zabbix repositories
  apt:
    deb: "{{ zabbix_repo_url }}"
    state: present

- name: Install zabbix-agent
  apt:
    name:
      - zabbix-agent
    state: present
    update_cache: true